on:
  push:
    tags:      
      - 'v[0-9]+.[0-9]+.[0-9]+**alpha**'

name: Deploy Pre-Release Extension
jobs:
  deploy-prelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - run: pnpm install
      - run: npm run compile
      - uses: lannonbr/vsce-action@master
        with:
          args: "publish -p $VSCE_TOKEN --pre-release --no-dependencies"
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}