on:
  push:
      branches:
      - master
      - dev
  pull_request:
name: Test Extension
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run test