on:
  push:
      branches:
      - master
      - dev
  pull_request:
name: Test Extension
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout
      - run: npm install
      - name: Start xvfb only if it's Linux
      if: startsWith(matrix.os,'ubuntu')
      run: |
        /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        echo ">>> Started xvfb"
      shell: bash
      - run: npm run test